USE SocialGraph
GO
SET NOCOUNT ON;
--Adapted from https://cafewebmaster.com/list-hobbies-and-interests-text-database
DELETE FROM Staging.Interest;
DBCC CHECKIDENT('Staging.Interest',RESEED); --Identity used to set number of interests


INSERT INTO Staging.Interest(InterestName) VALUES ('3D printing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Acting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Aeromodeling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Air sports');
INSERT INTO Staging.Interest(InterestName) VALUES ('Airbrushing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Aircraft Spotting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Airsoft');
INSERT INTO Staging.Interest(InterestName) VALUES ('Airsofting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Amateur astronomy');
INSERT INTO Staging.Interest(InterestName) VALUES ('Amateur geology');
INSERT INTO Staging.Interest(InterestName) VALUES ('Amateur Radio');
INSERT INTO Staging.Interest(InterestName) VALUES ('Football');
INSERT INTO Staging.Interest(InterestName) VALUES ('Animals/pets/dogs');
INSERT INTO Staging.Interest(InterestName) VALUES ('Antiquing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Antiquities');
INSERT INTO Staging.Interest(InterestName) VALUES ('Aqua-lung');
INSERT INTO Staging.Interest(InterestName) VALUES ('Archery');
INSERT INTO Staging.Interest(InterestName) VALUES ('Art');
INSERT INTO Staging.Interest(InterestName) VALUES ('Arts');
INSERT INTO Staging.Interest(InterestName) VALUES ('Astrology');
INSERT INTO Staging.Interest(InterestName) VALUES ('Astronomy');
INSERT INTO Staging.Interest(InterestName) VALUES ('Audiophilia');
INSERT INTO Staging.Interest(InterestName) VALUES ('Auto racing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Backgammon');
INSERT INTO Staging.Interest(InterestName) VALUES ('Backpacking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Badminton');
INSERT INTO Staging.Interest(InterestName) VALUES ('Base Jumping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Baseball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Basketball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Beach Volleyball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Beachcombing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Beadwork');
INSERT INTO Staging.Interest(InterestName) VALUES ('Beatboxing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Beekeeping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bell Ringing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Belly Dancing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bicycle Polo');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bicycling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Billiards');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bird watching');
INSERT INTO Staging.Interest(InterestName) VALUES ('Birdwatching');
INSERT INTO Staging.Interest(InterestName) VALUES ('Blacksmithing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Blogging');
INSERT INTO Staging.Interest(InterestName) VALUES ('BMX');
INSERT INTO Staging.Interest(InterestName) VALUES ('Board games');
INSERT INTO Staging.Interest(InterestName) VALUES ('BoardGames');
INSERT INTO Staging.Interest(InterestName) VALUES ('Boating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Body Building');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bonsai Tree');
INSERT INTO Staging.Interest(InterestName) VALUES ('Book collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bookbinding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Boomerangs');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bowling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Boxing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Breakdancing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Brewing Beer');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bridge');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bridge Building');
INSERT INTO Staging.Interest(InterestName) VALUES ('Building Dollhouses');
INSERT INTO Staging.Interest(InterestName) VALUES ('Bus spotting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Butterfly Watching');
INSERT INTO Staging.Interest(InterestName) VALUES ('Button Collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cake Decorating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Calligraphy');
INSERT INTO Staging.Interest(InterestName) VALUES ('Camping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Candle making');
INSERT INTO Staging.Interest(InterestName) VALUES ('Canoeing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Car Racing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Card collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cartooning');
INSERT INTO Staging.Interest(InterestName) VALUES ('Casino Gambling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cave Diving');
INSERT INTO Staging.Interest(InterestName) VALUES ('Ceramics');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cheerleading');
INSERT INTO Staging.Interest(InterestName) VALUES ('Chess');
INSERT INTO Staging.Interest(InterestName) VALUES ('Church activities');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cigar Smoking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Climbing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cloud Watching');
INSERT INTO Staging.Interest(InterestName) VALUES ('Coin Collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Antiques');
INSERT INTO Staging.Interest(InterestName) VALUES ('Artwork');
INSERT INTO Staging.Interest(InterestName) VALUES ('Hats');
INSERT INTO Staging.Interest(InterestName) VALUES ('Music Albums');
INSERT INTO Staging.Interest(InterestName) VALUES ('Records');
INSERT INTO Staging.Interest(InterestName) VALUES ('Swords');
INSERT INTO Staging.Interest(InterestName) VALUES ('Coloring');
INSERT INTO Staging.Interest(InterestName) VALUES ('Comic books');
INSERT INTO Staging.Interest(InterestName) VALUES ('Compose Music');
INSERT INTO Staging.Interest(InterestName) VALUES ('Computer activities');
INSERT INTO Staging.Interest(InterestName) VALUES ('Computer programming');
INSERT INTO Staging.Interest(InterestName) VALUES ('Conworlding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cooking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cosplay');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cosplaying');
INSERT INTO Staging.Interest(InterestName) VALUES ('Couponing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Crafts');
INSERT INTO Staging.Interest(InterestName) VALUES ('Creative writing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cricket');
INSERT INTO Staging.Interest(InterestName) VALUES ('Crochet');
INSERT INTO Staging.Interest(InterestName) VALUES ('Crocheting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cross-Stitch');
INSERT INTO Staging.Interest(InterestName) VALUES ('Crossword Puzzles');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cryptography');
INSERT INTO Staging.Interest(InterestName) VALUES ('Cycling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Dancing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Darts');
INSERT INTO Staging.Interest(InterestName) VALUES ('Debate');
INSERT INTO Staging.Interest(InterestName) VALUES ('Diecast Collectibles');
INSERT INTO Staging.Interest(InterestName) VALUES ('Digital arts');
INSERT INTO Staging.Interest(InterestName) VALUES ('Digital Photography');
INSERT INTO Staging.Interest(InterestName) VALUES ('Disc golf');
INSERT INTO Staging.Interest(InterestName) VALUES ('Do it yourself');
INSERT INTO Staging.Interest(InterestName) VALUES ('Dodgeball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Dog sport');
INSERT INTO Staging.Interest(InterestName) VALUES ('Dolls');
INSERT INTO Staging.Interest(InterestName) VALUES ('Dominoes');
INSERT INTO Staging.Interest(InterestName) VALUES ('Dowsing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Drama');
INSERT INTO Staging.Interest(InterestName) VALUES ('Drawing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Driving');
INSERT INTO Staging.Interest(InterestName) VALUES ('Dumpster Diving');
INSERT INTO Staging.Interest(InterestName) VALUES ('Eating out');
INSERT INTO Staging.Interest(InterestName) VALUES ('Educational Courses');
INSERT INTO Staging.Interest(InterestName) VALUES ('Electronics');
INSERT INTO Staging.Interest(InterestName) VALUES ('Element collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Embroidery');
INSERT INTO Staging.Interest(InterestName) VALUES ('Entertaining');
INSERT INTO Staging.Interest(InterestName) VALUES ('Equestrianism');
INSERT INTO Staging.Interest(InterestName) VALUES ('Exercise');
INSERT INTO Staging.Interest(InterestName) VALUES ('Exhibition drill');
INSERT INTO Staging.Interest(InterestName) VALUES ('Falconry');
INSERT INTO Staging.Interest(InterestName) VALUES ('Fast cars');
INSERT INTO Staging.Interest(InterestName) VALUES ('Felting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Fencing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Field hockey');
INSERT INTO Staging.Interest(InterestName) VALUES ('Figure skating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Fire Poi');
INSERT INTO Staging.Interest(InterestName) VALUES ('Fishing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Fishkeeping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Flag Football');
INSERT INTO Staging.Interest(InterestName) VALUES ('Floorball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Floral Arrangements');
INSERT INTO Staging.Interest(InterestName) VALUES ('Flower arranging');
INSERT INTO Staging.Interest(InterestName) VALUES ('Flower and pressing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Flying');
INSERT INTO Staging.Interest(InterestName) VALUES ('Foraging');
INSERT INTO Staging.Interest(InterestName) VALUES ('Fossil hunting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Four Wheeling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Aquariums');
INSERT INTO Staging.Interest(InterestName) VALUES ('Frisbee Golf');
INSERT INTO Staging.Interest(InterestName) VALUES ('Gambling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Games');
INSERT INTO Staging.Interest(InterestName) VALUES ('Gaming');
INSERT INTO Staging.Interest(InterestName) VALUES ('Garage Saleing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Gardening');
INSERT INTO Staging.Interest(InterestName) VALUES ('Genealogy');
INSERT INTO Staging.Interest(InterestName) VALUES ('Geocaching');
INSERT INTO Staging.Interest(InterestName) VALUES ('Ghost hunting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Glassblowing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Go Kart Racing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Golf');
INSERT INTO Staging.Interest(InterestName) VALUES ('Golfing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Graffiti');
INSERT INTO Staging.Interest(InterestName) VALUES ('Grip Strength');
INSERT INTO Staging.Interest(InterestName) VALUES ('Guitar');
INSERT INTO Staging.Interest(InterestName) VALUES ('Gun Collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Gunsmithing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Gymnastics');
INSERT INTO Staging.Interest(InterestName) VALUES ('Gyotaku');
INSERT INTO Staging.Interest(InterestName) VALUES ('Handball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Handwriting Analysis');
INSERT INTO Staging.Interest(InterestName) VALUES ('Hang gliding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Herping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Hiking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Home Brewing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Home Repair');
INSERT INTO Staging.Interest(InterestName) VALUES ('Home Theater');
INSERT INTO Staging.Interest(InterestName) VALUES ('Homebrewing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Hooping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Horse riding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Hot air ballooning');
INSERT INTO Staging.Interest(InterestName) VALUES ('Hula Hooping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Hunting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Ice hockey');
INSERT INTO Staging.Interest(InterestName) VALUES ('Ice skating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Iceskating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Illusion');
INSERT INTO Staging.Interest(InterestName) VALUES ('Impersonations');
INSERT INTO Staging.Interest(InterestName) VALUES ('Inline skating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Insect collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Internet');
INSERT INTO Staging.Interest(InterestName) VALUES ('Inventing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Jet Engines');
INSERT INTO Staging.Interest(InterestName) VALUES ('Jewelry Making');
INSERT INTO Staging.Interest(InterestName) VALUES ('Jigsaw Puzzles');
INSERT INTO Staging.Interest(InterestName) VALUES ('Jogging');
INSERT INTO Staging.Interest(InterestName) VALUES ('Judo');
INSERT INTO Staging.Interest(InterestName) VALUES ('Juggling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Jukskei');
INSERT INTO Staging.Interest(InterestName) VALUES ('Jump Roping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Kabaddi');
INSERT INTO Staging.Interest(InterestName) VALUES ('Kart racing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Kayaking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Keep A Journal');
INSERT INTO Staging.Interest(InterestName) VALUES ('Kitchen Chemistry');
INSERT INTO Staging.Interest(InterestName) VALUES ('Kite Boarding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Kite flying');
INSERT INTO Staging.Interest(InterestName) VALUES ('Kites');
INSERT INTO Staging.Interest(InterestName) VALUES ('Kitesurfing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Knapping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Knife making');
INSERT INTO Staging.Interest(InterestName) VALUES ('Knife throwing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Knitting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Knotting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Lacemaking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Lacrosse');
INSERT INTO Staging.Interest(InterestName) VALUES ('Lapidary');
INSERT INTO Staging.Interest(InterestName) VALUES ('LARPing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Laser tag');
INSERT INTO Staging.Interest(InterestName) VALUES ('Lasers');
INSERT INTO Staging.Interest(InterestName) VALUES ('Lawn Darts');
INSERT INTO Staging.Interest(InterestName) VALUES ('Learn to Play Poker');
INSERT INTO Staging.Interest(InterestName) VALUES ('Learning A Foreign Language');
INSERT INTO Staging.Interest(InterestName) VALUES ('Learning An Instrument');
INSERT INTO Staging.Interest(InterestName) VALUES ('Learning To Pilot A Plane');
INSERT INTO Staging.Interest(InterestName) VALUES ('Leather crafting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Leathercrafting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Lego building');
INSERT INTO Staging.Interest(InterestName) VALUES ('Legos');
INSERT INTO Staging.Interest(InterestName) VALUES ('Letterboxing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Listening to music');
INSERT INTO Staging.Interest(InterestName) VALUES ('Locksport');
INSERT INTO Staging.Interest(InterestName) VALUES ('Machining');
INSERT INTO Staging.Interest(InterestName) VALUES ('Macramé');
INSERT INTO Staging.Interest(InterestName) VALUES ('Macrame');
INSERT INTO Staging.Interest(InterestName) VALUES ('Magic');
INSERT INTO Staging.Interest(InterestName) VALUES ('Mahjong');
INSERT INTO Staging.Interest(InterestName) VALUES ('Making Model Cars');
INSERT INTO Staging.Interest(InterestName) VALUES ('Marbles');
INSERT INTO Staging.Interest(InterestName) VALUES ('Marksmanship');
INSERT INTO Staging.Interest(InterestName) VALUES ('Martial arts');
INSERT INTO Staging.Interest(InterestName) VALUES ('Matchstick Modeling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Meditation');
INSERT INTO Staging.Interest(InterestName) VALUES ('Metal detecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Meteorology');
INSERT INTO Staging.Interest(InterestName) VALUES ('Microscopy');
INSERT INTO Staging.Interest(InterestName) VALUES ('Mineral collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Model aircraft');
INSERT INTO Staging.Interest(InterestName) VALUES ('Model building');
INSERT INTO Staging.Interest(InterestName) VALUES ('Model Railroading');
INSERT INTO Staging.Interest(InterestName) VALUES ('Model Rockets');
INSERT INTO Staging.Interest(InterestName) VALUES ('Modeling Ships');
INSERT INTO Staging.Interest(InterestName) VALUES ('Models');
INSERT INTO Staging.Interest(InterestName) VALUES ('Motor sports');
INSERT INTO Staging.Interest(InterestName) VALUES ('Motorcycles');
INSERT INTO Staging.Interest(InterestName) VALUES ('Mountain Biking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Mountain Climbing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Mountaineering');
INSERT INTO Staging.Interest(InterestName) VALUES ('Movie memorabilia');
INSERT INTO Staging.Interest(InterestName) VALUES ('Mushroom hunting/Mycology');
INSERT INTO Staging.Interest(InterestName) VALUES ('Musical Instruments');
INSERT INTO Staging.Interest(InterestName) VALUES ('Nail Art');
INSERT INTO Staging.Interest(InterestName) VALUES ('Needlepoint');
INSERT INTO Staging.Interest(InterestName) VALUES ('Netball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Nordic skating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Orienteering');
INSERT INTO Staging.Interest(InterestName) VALUES ('Origami');
INSERT INTO Staging.Interest(InterestName) VALUES ('Owning An Antique Car');
INSERT INTO Staging.Interest(InterestName) VALUES ('Paintball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Painting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Papermache');
INSERT INTO Staging.Interest(InterestName) VALUES ('Papermaking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Parachuting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Paragliding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Parkour');
INSERT INTO Staging.Interest(InterestName) VALUES ('People Watching');
INSERT INTO Staging.Interest(InterestName) VALUES ('Photography');
INSERT INTO Staging.Interest(InterestName) VALUES ('Piano');
INSERT INTO Staging.Interest(InterestName) VALUES ('Pigeon racing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Pinochle');
INSERT INTO Staging.Interest(InterestName) VALUES ('Pipe Smoking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Planking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Playing music');
INSERT INTO Staging.Interest(InterestName) VALUES ('Playing musical instruments');
INSERT INTO Staging.Interest(InterestName) VALUES ('Playing team sports');
INSERT INTO Staging.Interest(InterestName) VALUES ('Poker');
INSERT INTO Staging.Interest(InterestName) VALUES ('Pole Dancing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Polo');
INSERT INTO Staging.Interest(InterestName) VALUES ('Pottery');
INSERT INTO Staging.Interest(InterestName) VALUES ('Powerboking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Protesting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Puppetry');
INSERT INTO Staging.Interest(InterestName) VALUES ('Puzzles');
INSERT INTO Staging.Interest(InterestName) VALUES ('Pyrotechnics');
INSERT INTO Staging.Interest(InterestName) VALUES ('Quilting');
INSERT INTO Staging.Interest(InterestName) VALUES ('R/C Boats');
INSERT INTO Staging.Interest(InterestName) VALUES ('R/C Cars');
INSERT INTO Staging.Interest(InterestName) VALUES ('R/C Helicopters');
INSERT INTO Staging.Interest(InterestName) VALUES ('R/C Planes');
INSERT INTO Staging.Interest(InterestName) VALUES ('Racing Pigeons');
INSERT INTO Staging.Interest(InterestName) VALUES ('Racquetball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Radio-controlled car racing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Rafting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Railfans');
INSERT INTO Staging.Interest(InterestName) VALUES ('Rappelling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Rapping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Reading');
INSERT INTO Staging.Interest(InterestName) VALUES ('Reading To The Elderly');
INSERT INTO Staging.Interest(InterestName) VALUES ('Record collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Relaxing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Renaissance Faire');
INSERT INTO Staging.Interest(InterestName) VALUES ('Renting movies');
INSERT INTO Staging.Interest(InterestName) VALUES ('Rescuing Animals');
INSERT INTO Staging.Interest(InterestName) VALUES ('Robotics');
INSERT INTO Staging.Interest(InterestName) VALUES ('Rock balancing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Rock climbing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Rock Collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Rockets');
INSERT INTO Staging.Interest(InterestName) VALUES ('Roleplaying');
INSERT INTO Staging.Interest(InterestName) VALUES ('Roller derby');
INSERT INTO Staging.Interest(InterestName) VALUES ('Roller skating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Rugby');
INSERT INTO Staging.Interest(InterestName) VALUES ('Running');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sailing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sand art');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sand Castles');
INSERT INTO Staging.Interest(InterestName) VALUES ('Scrapbooking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Scuba diving');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sculling or Rowing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sculpting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sea glass collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Seashell collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Self Defense');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sewing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Shark Fishing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Shooting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Shooting sport');
INSERT INTO Staging.Interest(InterestName) VALUES ('Shopping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Shortwave listening');
INSERT INTO Staging.Interest(InterestName) VALUES ('Singing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Skateboarding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Skeet Shooting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sketching');
INSERT INTO Staging.Interest(InterestName) VALUES ('Skiing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Skimboarding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sky Diving');
INSERT INTO Staging.Interest(InterestName) VALUES ('Skydiving');
INSERT INTO Staging.Interest(InterestName) VALUES ('Slack Lining');
INSERT INTO Staging.Interest(InterestName) VALUES ('Slacklining');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sleeping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Slingshots');
INSERT INTO Staging.Interest(InterestName) VALUES ('Slot car racing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Snorkeling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Snowboarding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Soap Making');
INSERT INTO Staging.Interest(InterestName) VALUES ('Soapmaking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Soccer');
INSERT INTO Staging.Interest(InterestName) VALUES ('Socializing ');
INSERT INTO Staging.Interest(InterestName) VALUES ('Speed skating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Spelunkering');
INSERT INTO Staging.Interest(InterestName) VALUES ('Sports');
INSERT INTO Staging.Interest(InterestName) VALUES ('Squash');
INSERT INTO Staging.Interest(InterestName) VALUES ('Stamp Collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Stand-up comedy');
INSERT INTO Staging.Interest(InterestName) VALUES ('Stone collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Stone skipping');
INSERT INTO Staging.Interest(InterestName) VALUES ('Storm Chasing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Storytelling');
INSERT INTO Staging.Interest(InterestName) VALUES ('String Figures');
INSERT INTO Staging.Interest(InterestName) VALUES ('Surf Fishing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Surfing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Survival');
INSERT INTO Staging.Interest(InterestName) VALUES ('Swimming');
INSERT INTO Staging.Interest(InterestName) VALUES ('Table football');
INSERT INTO Staging.Interest(InterestName) VALUES ('Table tennis');
INSERT INTO Staging.Interest(InterestName) VALUES ('Taekwondo');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tai chi');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tatting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Taxidermy');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tea Tasting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tennis');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tesla Coils');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tetris');
INSERT INTO Staging.Interest(InterestName) VALUES ('Textiles');
INSERT INTO Staging.Interest(InterestName) VALUES ('Texting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tombstone Rubbing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tool Collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tour skating');
INSERT INTO Staging.Interest(InterestName) VALUES ('Toy Collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Train Collecting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Train Spotting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Trainspotting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Traveling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Treasure Hunting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Trekkie');
INSERT INTO Staging.Interest(InterestName) VALUES ('Triathlon');
INSERT INTO Staging.Interest(InterestName) VALUES ('Tutoring Children');
INSERT INTO Staging.Interest(InterestName) VALUES ('TV watching');
INSERT INTO Staging.Interest(InterestName) VALUES ('Ultimate Frisbee');
INSERT INTO Staging.Interest(InterestName) VALUES ('Urban exploration');
INSERT INTO Staging.Interest(InterestName) VALUES ('Vehicle restoration');
INSERT INTO Staging.Interest(InterestName) VALUES ('Video gaming');
INSERT INTO Staging.Interest(InterestName) VALUES ('Videophilia');
INSERT INTO Staging.Interest(InterestName) VALUES ('Vintage cars');
INSERT INTO Staging.Interest(InterestName) VALUES ('Violin');
INSERT INTO Staging.Interest(InterestName) VALUES ('Volleyball');
INSERT INTO Staging.Interest(InterestName) VALUES ('Volunteer');
INSERT INTO Staging.Interest(InterestName) VALUES ('Walking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Warhammer');
INSERT INTO Staging.Interest(InterestName) VALUES ('Watching movies');
INSERT INTO Staging.Interest(InterestName) VALUES ('Watching sporting events');
INSERT INTO Staging.Interest(InterestName) VALUES ('Water sports');
INSERT INTO Staging.Interest(InterestName) VALUES ('Weather Watcher');
INSERT INTO Staging.Interest(InterestName) VALUES ('Web surfing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Weightlifting');
INSERT INTO Staging.Interest(InterestName) VALUES ('Windsurfing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Wine Making');
INSERT INTO Staging.Interest(InterestName) VALUES ('Wingsuit Flying');
INSERT INTO Staging.Interest(InterestName) VALUES ('Wood carving');
INSERT INTO Staging.Interest(InterestName) VALUES ('Woodworking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Working on cars');
INSERT INTO Staging.Interest(InterestName) VALUES ('World Record Breaking');
INSERT INTO Staging.Interest(InterestName) VALUES ('Worldbuilding');
INSERT INTO Staging.Interest(InterestName) VALUES ('Wrestling');
INSERT INTO Staging.Interest(InterestName) VALUES ('Writing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Writing Music');
INSERT INTO Staging.Interest(InterestName) VALUES ('Writing Songs');
INSERT INTO Staging.Interest(InterestName) VALUES ('Yo-yoing');
INSERT INTO Staging.Interest(InterestName) VALUES ('Yoga');
INSERT INTO Staging.Interest(InterestName) VALUES ('YoYo');
INSERT INTO Staging.Interest(InterestName) VALUES ('Ziplining');
INSERT INTO Staging.Interest(InterestName) VALUES ('Zumba');

SELECT COUNT(*) FROM Staging.Interest;